# Generated by Django 4.0.3 on 2022-03-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.PositiveIntegerField(verbose_name='Серия карты')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер карты')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('duration', models.PositiveIntegerField(choices=[(1, '1 месяц'), (6, '6 месяцев'), (12, '1 год')], verbose_name='Длительность действия')),
                ('end_date', models.DateField(blank=True, verbose_name='Дата окончания активности')),
                ('last_use', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс')),
                ('status', models.CharField(choices=[('active', 'Активирована'), ('inactivated', 'Не активирована'), ('overdue', 'Просрочена')], max_length=255, verbose_name='Статус карты')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
