# Generated by Django 4.0.3 on 2022-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания активности'),
        ),
    ]
