# Generated by Django 4.0.3 on 2022-03-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название покупки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость покупки')),
                ('residual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Остаток на карте')),
                ('buy_time', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to='cards.card', verbose_name='Банковская карта')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
