# Generated by Django 4.0.3 on 2022-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_release_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '1 месяц'), (6, '6 месяцев'), (12, '1 год')], verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Номер карты'),
        ),
    ]
